
Get http://192.168.100.9:3000/

#### Hola

POST http://localhost:3000/folderPrueba-folderPrueba1
Content-Type: application/json

{
    "type": "file",
    "nombre": "prueba.jpeg",
    "data": ""
}

###

DELETE http:///?type=file&nombre=abuela.ai


###
GET http://192.168.100.9:3000/download/files/?nombre=index.html